### PR TITLE
Revert "implemented randomness for rows, cols, and verticality"

### PR DESCRIPTION
**Pull request by Evdemonm**
Reverts cs361fall2018/project-team-31#17 Sorry to do this but I don't believe there was a review on that merge request, I could be wrong though, its on the rubric for points.

### CODE REVIEW

**Comment by iKiwiz** [comment]
I don't know who merged but I think Anais gave a review. I could be wrong though.

**Comment by Evdemonm** [comment]
Well, I doubt it matters but can someone leave a review on this one, just in case?

**Comment by Evdemonm** [comment]
Oh yeah I there is something part of the random function that may break it, I am not sure if the +1 on the end of columns or rows in necessary and it may give bad results on J or 10.

**Comment by Evdemonm** [comment]
Yeah sorry I was being dumb, there was a review I just looked for the green check mark that was not there.

**Pull request closed without merging**
